### ISSUE TITLE
leaked resource spam

### ISSUE THREAD

**Issue by Xplodin** [Aureljz/WhenDungeonsArise--Forge#19]
Leaked resource: 'dungeons_arise:structures/foundry/foundry_corridor_2_stairway.nbt' loaded from pack: 'DungeonsArise-1.19.2-2.1.54-release.jar'
java.lang.Exception
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.packs.resources.FallbackResourceManager$LeakedResourceWarningInputStream.<init>(FallbackResourceManager.java:109)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.packs.resources.FallbackResourceManager.m_215409_(FallbackResourceManager.java:91)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.packs.resources.Resource.m_215507_(Resource.java:36)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.packs.resources.ResourceProvider.m_215595_(ResourceProvider.java:24)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230427_(StructureTemplateManager.java:533)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230425_(StructureTemplateManager.java:102)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230407_(StructureTemplateManager.java:92)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230359_(StructureTemplateManager.java:80)
        at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_227299_(SinglePoolElement.java:85)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_214015_(SinglePoolElement.java:118)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:58)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.m_192753_(PiecesContainer.java:73)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.StructureStart.m_226857_(StructureStart.java:56)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.chunk.storage.ChunkSerializer.m_188254_(ChunkSerializer.java:474)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.chunk.storage.ChunkSerializer.m_188230_(ChunkSerializer.java:206)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ChunkMap.m_214889_(ChunkMap.java:563)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:535)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:543)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:267)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:751)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
        at java.base/java.lang.Thread.run(Thread.java:833)

also the game lags heavily when I get near a structure thats underground.
nether themed with piglin brutes wearing netherite armor.

that logspam is dedicated server btw

**Comment by Xplodin** [comment]
ignore the logspam, isnt with the mod
